[env]
PORT = "8000"

[config]
skip_core_tasks = true

# ---- BASIC ----

[tasks.watch]
description = "Watch files and recompile the project on change"
script = '''
cargo make build
cargo make tailwind
'''
watch = true

[tasks.serve]
description = "Start server"
install_crate = { crate_name = "live-server", binary = "live-server", test_arg = "--help" }
command = "live-server"
args = ["-h", "0.0.0.0", "-p", "${PORT}"]

[tasks.verify]
description = "Format, lint with Clippy and run tests"
dependencies = ["fmt", "clippy", "test_h_firefox"]

# ---- BUILD ----

[tasks.build]
description = "Build with wasm-pack"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "package", "--dev"]

[tasks.tailwind]
description = "Build tailwind css file 'tw.css'"
command = "tailwindcss"
args = ["-o", "tw.css"]

[tasks.build_release]
description = "Build with wasm-pack in release mode"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "package"]