[package]
name = "axum-server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.89"
tokio = { version = "1.0", features = ["full"] }
the_library = {path = "../the_library"}